services:
  fe:
    container_name: ccss-fe.dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - be

  be:
    container_name: ccss-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - db

  db:
    container_name: ccss-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: ccss
      POSTGRES_USER: ccss
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d