services:
  fe:
    container_name: ccss-fe
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - be

  be:
    container_name: ccss-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db
    environment:
      - DEBUG=False

  db:
    container_name: ccss-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ccss
      POSTGRES_USER: ccss
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d